[package]
name = "nft-ptr-lib"
version = "0.1.0"
authors = ["Zhuowei Zhang <zhuowei@worthdoingbadly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
